### ISSUE TITLE
WaitCondition received failed message: 'attempting to apply changes to the targeted Ops Manager' for uniqueId: xxxxxxxxx

### ISSUE THREAD

**Issue by abhaychaware** [aws-quickstart/quickstart-pivotal-cloudfoundry#11]
Hello
I have tried several times, and still not able to set up PCF ( Starter mode ) on AWS cloud using the Cloud Formation template. Please find attached the event log. Could you please help me on priority ?  

AWS::CloudFormation::WaitCondition   WaitCondition   WaitCondition received failed message: 'attempting to apply changes to the targeted Ops Manager' for uniqueId: xxxxxxxxxxxxx (masked) 

Please find attached the event file.

[Stack-rollback.txt](https://github.com/aws-quickstart/quickstart-pivotal-cloudfoundry/files/1490182/Stack-rollback.txt)

![pcf quickstart parameters](https://user-images.githubusercontent.com/4303899/33057574-a0a6d25e-ceb1-11e7-8701-5570f42b9289.JPG)

**Comment by boparp-pivotal** [comment]
Hi Abhay, can you please set your "ForwardLogOutput" to true and try again and if it fails, send me the log file from CloudWatch?

**Comment by abhaychaware** [comment]
Okay. I'll do that and post the logs here. 
Thanks !

**Comment by abhaychaware** [comment]
Here are the log files (redacted)
Thanks for your help.

[logs.zip](https://github.com/aws-quickstart/quickstart-pivotal-cloudfoundry/files/1491358/logs.zip)

**Comment by platinumnj** [comment]
I am following this closely as I too am receiving the same issue.

**Comment by boparp-pivotal** [comment]
Hi Abhay, I suspect there might be a problem with your Domain. Per the log files, _opsman.[YOUR_DOMAIN]_ is resolved correctly, but _*.sys.[YOUR_DOMAIN]_ and _*.apps.[YOUR_DOMAIN]_ is not resolved. Can you please verify if you followed the steps in the Deployment guide correctly, especially the domain setup?  
The CFN template sets up all the subdomains for PCF. It maps _opsman.[YOUR_DOMAIN]_ to the public EIP for your Ops Manager and maps _*.sys.[YOUR_DOMAIN]_ and _*.apps.[YOUR_DOMAIN]_ to the ELB. The latter is not working as it should, in your case. 
I just did a successful deployment in AWS region us-west-2, which is the same region you are trying in. 
Please let us know what you find.

**Comment by platinumnj** [comment]
Did you by any chance ensure that the wild card is setup for your SSL?

That was an error I ran into.

" The only place where success
comes before work is in the
dictionary"

**Comment by boparp-pivotal** [comment]
for your ssl cert, please ensure it supports at least these domains: `*.sys.[YOUR_DOMAIN] , *.apps.[YOUR_DOMAIN]`
@platinumnj  is your issue resolved?

**Comment by abhaychaware** [comment]
I think you are right. I had overlooked the part that says it needs a already registered domain in addition to the hosted zone.  I've registered the domain now, it would take some time to complete the registration and then i'll start setting up the stack again. I'll keep you posted. Thanks for your help !

**Comment by platinumnj** [comment]
My issue is resolved. Yes - The wait condition kept failing due to the default limit values for US-EAST region of Ec2 instances not being increased.

**Comment by boparp-pivotal** [comment]
@platinumnj good to know
@abhaychaware while you are setting up the domains correctly, please also check your EC2 Limits and ensure you have the required quota in your AWS region to support the PCF deployment.

**Comment by abhaychaware** [comment]
I increased the EC2 limits to 40, and launched the starter package, but it failed again !  Upon checking logs looks like it failed with the Limit Error again - 

Unknown CPI error \'Unknown\' with message \'Your quota allows for 0 more running instance(s). You requested at least 1\' in \'create_vm\' CPI method (00:00:08)\n Failed creating missing vms

Strange. I read that Starter deployment creates 22 instances then why this error ?

-abhay

**Comment by platinumnj** [comment]
Did you increase the RDS limits as well?

On Nov 23, 2017 9:40 PM, "abhaychaware" <notifications@github.com> wrote:

I increased the EC2 limits to 40, and launched the starter package, but it
failed again ! Upon checking logs looks like it failed with the Limit Error
again -

Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more
running instance(s). You requested at least 1' in 'create_vm' CPI method
(00:00:08)\n Failed creating missing vms

Strange. I read that Starter deployment creates 22 instances then why this
error ?

-abhay

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/aws-quickstart/quickstart-pivotal-cloudfoundry/issues/11#issuecomment-346728820>,
or mute the thread

**Comment by abhaychaware** [comment]
RDS seems to be okay -  It says,

DB Instances (1/40)
Allocated storage (100.00 GB/100.00 TB)

I also noticed another error on SSL Validation.  i had accidently left 'skipSSLValidation' to 'false' in the last run.    I've now set  it to 'true' and started again.   Lets see if it suceeds now.

But the question remains unanswered - how many instances does it create in EC2 for Starter deployment ?   I've specified t2.medium instance size, would it create all instances of this same size ?

**Comment by platinumnj** [comment]
Starter creates 22 instances.  And the size is only for your Nat instance.
It will create many different instance sizes.  Let me know evrrythjgn
cewployed successfully for me but I also can't access apps.pcfdomain.
which is weird.  I can get in opsman .pcfdomain however.

On Nov 23, 2017 10:35 PM, "abhaychaware" <notifications@github.com> wrote:

RDS seems to be okay - It says,

DB Instances (1/40)
Allocated storage (100.00 GB/100.00 TB)

I also noticed another error on SSL Validation. i had accidently left
'skipSSLValidation' to 'false' in the last run. I've now set it to 'true'
and started again. Lets see if it suceeds now.

But the question remains unanswered - how many instances does it create in
EC2 for Starter deployment ? I've specified t2.medium instance size, would
it create all instances of this same size ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/aws-quickstart/quickstart-pivotal-cloudfoundry/issues/11#issuecomment-346736339>,
or mute the thread

**Comment by boparp-pivotal** [comment]
@abhaychaware Starter creates 22 instances, but they are of various different kinds. It's possible that some of your instance types are limited to a very few number and PCF needs more. 
Also remember, that the PCF installation creates several transient VMs that play a role only during the installation, and are deleted at the end of install. 
@platinumnj PCF Apps Manager link is always apps.[PCF_SYSTEM_DOMAIN]
In the Quick Start, the PCF_SYSTEM_DOMAIN = sys.[YOUR_PCF_DOMAIN]
From the Ops Manager, you can click on the CF ERT tile and look at the Domain values.

**Comment by abhaychaware** [comment]
Oh. It might be hitting limits on other type of instances then.  From your setup, could you share the number of instances per type ? I might need to get the limits increased on those as well. 

But if it created 22 for you, then why did it show me 38 instances , is still a puzzle.

**Comment by boparp-pivotal** [comment]
@abhaychaware if you see 38 instances created by the QS, then you likely chose the multi-AZ deployment, and not the Starter.

**Comment by boparp-pivotal** [comment]
The standard 40 instance limit should be enough for the Starter, but not for the 2-AZ deployment for the reasons I mentioned above.

**Comment by abhaychaware** [comment]
No, it was a starter deployment. Please check my post above - with screenshot.

**Comment by abhaychaware** [comment]
Also, do you know approx. cost of using AWS infra for using the starter deployment say for a month with 100% utilization  ? Including the transient VMs and all services like S3, RDS, EC2 and ESB ?

**Comment by abhaychaware** [comment]
Finally, the setup completed successfully. and it shows 22 running instances.  Thanks for your help boparp-pivotal and platinumnj.
Could you please help me with the cost indicator ? Thanks !

**Comment by boparp-pivotal** [comment]
Glad your install is successful. The EC2 dashboard shows you all the resources created. You can run the AWS pricing calculator with that. To get a correct estimate, please make sure you only feed into the calculator the resources created by PCF. 
https://calculator.s3.amazonaws.com/index.html

**Comment by abhaychaware** [comment]
Sure i'll do that. I was hoping that you might have a rough estimate $ number, so i wouldn't have to go through the calculation exercise.

**Comment by abhaychaware** [comment]
Thanks !
