### ISSUE TITLE
Start/Stop the PCF QuickStart Environment on AWS

### ISSUE THREAD

**Issue by abhaychaware** [aws-quickstart/quickstart-pivotal-cloudfoundry#13]
Is there an easy way to shut down and start-up the PCF QuickStart Environment on AWS? I saw the Pivotal documentation where it recommends using BOSH CLI, but not sure if they are applicable to PCF Quick Start environment, and if yes, any documentation around that.

Thanks
Abhay

**Comment by boparp-pivotal** [comment]
The BOSH CLI is the recommended way to stop/start any BOSH deployments. The Quick Start runs scripts that automate the PCF install, which otherwise you'd do manually. The resulting PCF is essentially the same. The BOSH CLI approach to stop/start PCF would certainly work. There's a command called "bosh2 stop --hard". This command will delete all the PCF VM's but leave only the BOSH Director and Ops Manager VM running. What remains is the persistent disks. When you run "bosh2 start" it will restore all the VM's and the state of PCF. You could do this to save infra costs in a Dev/Test env. Take a look at this: https://github.com/d4v3r/pcf-start-stop
I recommend using the new "bosh2" CLI, which should be already installed on the Ops Manager VM.

**Comment by abhaychaware** [comment]
I used these scripts and works well. But since it is discarding all the VMs on stop and recreating them on start, it is as good as deleting an recreating the stack and takes significant amount of time.   Instead , is there any option that stops ( not deletes ) and starts ( not creates ) all the instances, except for the bosh director of course.  I see that "bosh stop" command stops the services, but not the VMs. Is there any sequence in which the VMs need to be stopped/started ?  i can then write a script to that myself .

**Comment by boparp-pivotal** [comment]
@abhaychaware  BOSH has a HA feature that will automatically try to restart a vm that was shutdown manually. If you turn off that feature from Ops Manager then you may save some time by combining "bosh stop" (without the _--hard_ flag) and a script to stop the VM's, but you'll lose that level of HA. I suggest stick with the _--hard_ flag even though it takes longer.
Since you have made good progress with PCF+BOSH, I recommend you join the Cloud Foundry Slack. https://cloudfoundry.org/
For all your core CF/BOSH questions you could reach a wider audience and get a quicker response on CF Slack. 
For any AWS Quick Start (PCF) specific questions (issues with the QS deployment or to provide feedback to us on the QS or any questions for us at Pivotal about Pivotal's add-on features like Ops Manager, Apps Manager, etc), continue to post your questions here and we are happy to help. 
Are you evaluating PCF for any particular project?

**Comment by abhaychaware** [comment]
Thank you @boparp-pivotal for your help.  I'll take a look at the HA feature in Ops Manager.  Also i'll join the CF DL. 
I am a Cloud Architect and evaluating CF as a technology.  Specifically looking at docker support.  I have couple of questions around that and PCF, will create new questions for the same.
Thanks
